spring:
  application:
    name: Car Service
  profiles:
    active: store1
  datasource:
    url: "jdbc:mysql://localhost:3306/table"
    username: "root"
    password: "12345678"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true